### ISSUE TITLE
[BUG] Error "missing header rr-attempt" although this header exist in AMQP message

### ISSUE THREAD

**Issue by mqwerty** [spiral/jobs#49]
RoadRunner, PHP Application Server
Version: 2.4.18, 2020-05-23T19:45:45+0300

```php
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;
use PhpAmqpLib\Wire\AMQPTable;

chdir(__DIR__);
require_once __DIR__ . '/vendor/autoload.php';

$id = bin2hex(random_bytes(16));
$message = new AMQPMessage(
    'test',
    [
        'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT,
        'content_type' => 'application/octet-stream',
        'application_headers' => new AMQPTable(
            [
                'rr-id' => $id,
                'rr-attempt' => 0,
                'rr-delay' => 0,
                'rr-job' => 'local.test',
                'rr-maxAttempts' => 0,
                'rr-retryDelay' => 0,
                'rr-timeout' => 0,
            ]
        ),
    ]
);

$amqp = new AMQPStreamConnection('rabbitmq', '5672', 'guest', 'guest');
$amqp->channel()->basic_publish($message, 'local.test', 'local.test');
```

Screenshot from RabbitMQ admin panel:

![20200610_133723](https://user-images.githubusercontent.com/1752799/84258424-94fa7800-ab1f-11ea-8a73-9750a112aae9.png)

The same error when I send a message from the RabbitMQ admin panel.

**Comment by mqwerty** [comment]
RoadRunner config:
```yml
jobs:
  workers.command: "php /app/j.php"
  amqp.addr: amqp://guest:guest@rabbitmq:5672/
  pipelines:
    local:
      broker: "amqp"
      queue: "local.test"
      exchange: "local.test"
  consume: ["local"]
  dispatch:
    app-job-*.pipeline: "local"
```

RabbitMQ config:
```json
{
  "queues": [
    {
      "name": "local.test",
      "vhost": "/",
      "durable": true,
      "auto_delete": false,
      "arguments": {}
    }
  ],
  "bindings": [
    {
      "source": "local.test",
      "vhost": "/",
      "destination": "local.test",
      "destination_type": "queue",
      "routing_key": "local.test",
      "arguments": {}
    }
  ],
  "exchanges": [
    {
      "name": "local.test",
      "vhost": "/",
      "type": "direct",
      "durable": true,
      "auto_delete": false,
      "internal": false,
      "arguments": {}
    }
  ]
}
```
