### ISSUE TITLE
[BUG] Setting maxAttempts don't work

### ISSUE THREAD

**Issue by ogbofjnr** [spiral/jobs#53]
Version v1.1.3.

`maxAttempts ` don't work as in docs https://spiral.dev/docs/queue-jobs
```pipelines:
    local:
        broker: amqp
        queue: my-queue
        maxAttempts: 2
```

This this setup works instead:

```
dispatch:
    jobs-remote-*:
      pipeline: beanstalk
      Attempts: 5
      retryDelay: 10
      timeout: 10000
      delay: 10
 ```
Looks like somehow tag ```  `json:"maxAttempts,omitempty"``` don't make effect.
